### ISSUE TITLE
TI7 group stage games reported as bo3

### ISSUE THREAD

**Issue by Smitty-C** [enoch-ng/Dota2HelperBot#1]
Drafting notification messages are reported as best of 3, whereas it should be best of 2.

Example: The draft for TNC Pro Team vs. Evil Geniuses is now underway (Game 2 of 3).

Expected: The draft for TNC Pro Team vs. Evil Geniuses is now underway (Game 2 of 2).

**Comment by enoch-ng** [comment]
Unfortunately Valve's API data reports the matches as being a Bo3. TrackDota is having the same problem [due to this quirk]. I agree that this is undesirable but I can't think of an elegant way to solve it...
